import Navbar from "@/components/Navbar";
import "./globals.css";
import { Montserrat } from "next/font/google";
import { Provider } from "react-redux";
import store from "@/store/store";
import StoreProvider from "@/components/StoreProvider";

const montserrat = Montserrat({
    subsets: ["latin"],
    weight: ["300", "500", "700"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang='en'>
            <body className={montserrat.className}>
                <StoreProvider>
                    <Navbar />
                    <hr className='border-t-2 border-warning/90' />
                    {children}
                </StoreProvider>
            </body>
        </html>
    );
}
